name: clone
on:
  push:
    branches:
      - master
      - test
  workflow_dispatch: # for running manually in GitHub Actions GUI
    inputs:
      branch:

env:
  BRANCH: master

jobs:
  clone:
    name: clone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch || env.GITHUB_SHA }}
      - name: variables
        shell: bash
        run: |
          echo "GITHUB_SHA = ${{ env.GITHUB_SHA }}"
          git branch
          echo  "branch = ${{ inputs.branch }}"
